

language: java

jdk: openjdk12
services: postgresql

before_script:
  - psql -c 'create database support;' -U postgres
  - psql support
  - psql -h localhost -U postgres -d support -a -f "import/create.sql"

script:
  - javac -cp "import/lib/*" "import/src/com/siriusminerals/asana2postgres/Main.java"
  - java  -cp "import/src/com/siriusminerals/asana2postgres/Main"

cache:
  directories:
  - $HOME/.m2