language: java

jdk: openjdk11

services: postgresql


before_script:
  - psql -c 'create database support;' -U postgres
  - psql -h localhost -U postgres -d support -a -f "import/create.sql"
  - psql -c "CREATE USER $db_user WITH PASSWORD '$db_pass'";
  - psql -d support -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $db_user"

script:
  - javac -cp "import/lib/*" "import/src/main/java/Main.java"
  - cd import && gradle jar
  - cd "$TRAVIS_BUILD_DIR"/import/build/libs/ && java -jar asana2postgres-1.0.jar
  - javac -cp "sync/lib/*" "sync/src/main/java/Main.java"
  - cd sync && gradle jar
  - cd "$TRAVIS_BUILD_DIR"/sync/build/libs/ && java -jar asana-sync-1.0.jar
cache:
  directories:
  - $HOME/.m2
