
language: java



jdk: openjdk12


services: postgresql

before_script:
  - psql -c 'create database support;' -U postgres
  - psql -h localhost -U postgres -d support -a -f "import/create.sql"
  - psql -c "CREATE USER $db_user WITH PASSWORD '$db_pass'";
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE support TO $db_user";
  - psql -c "GRANT ALL PRIVILEGES ON TABLE public.tickets TO $db_user"

script:
  - javac -cp "import/lib/*" "import/src/com/siriusminerals/asana2postgres/Main.java"
  - java -jar Asana2Postgres.jar

cache:
  directories:
  - $HOME/.m2