dist: bionic

language: java

jdk: openjdk12
services: postgres

before_script:
  - sudo -i -u postgres
  - createdb support
  - -d support -f "import/create.sql"

script:
  - javac -cp "import/lib/*" "import/src/com/siriusminerals/asana2postgres/Main.java"
  - java  -cp "import/src/com/siriusminerals/asana2postgres/Main"

cache:
  directories:
  - $HOME/.m2